# Generated by Django 6.0.2 on 2026-02-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('homicide', 'Homicide'), ('fraud', 'Fraud'), ('cybercrime', 'Cybercrime'), ('robbery', 'Robbery'), ('burglary', 'Burglary'), ('drug_offense', 'Drug Offense'), ('sexual_offense', 'Sexual Offense'), ('vandalism', 'Vandalism'), ('kidnapping', 'Kidnapping'), ('arson', 'Arson'), ('corruption', 'Corruption'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('solved', 'Solved'), ('closed', 'Closed'), ('cold_case', 'Cold Case')], default='reported', max_length=30)),
                ('description', models.TextField()),
                ('weapons_used', models.CharField(blank=True, max_length=200)),
                ('modus_operandi', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_occurred', models.DateTimeField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('victim_count', models.PositiveIntegerField(default=1)),
                ('victim_details', models.TextField(blank=True)),
                ('evidence_notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crime_attachments/')),
                ('is_analyzed', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crime Report',
                'verbose_name_plural': 'Crime Reports',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('age_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('known_to_victim', models.BooleanField(default=False)),
                ('is_arrested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='crimes.crimereport')),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('statement', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='crimes.crimereport')),
            ],
            options={
                'verbose_name': 'Witness',
                'verbose_name_plural': 'Witnesses',
            },
        ),
    ]
