import os
import logging
from django.http                import FileResponse
from django.utils               import timezone
from rest_framework             import status
from rest_framework.views       import APIView
from rest_framework.response    import Response
from rest_framework.permissions import IsAuthenticated
from drf_spectacular.utils      import extend_schema, OpenApiExample

from apps.crimes.models         import CrimeReport
from apps.analysis.models       import AnalysisResult
from .models                    import GeneratedReport, ReportType, ReportFormat
from .serializers               import GeneratedReportSerializer
from .generators.pdf_generator  import (
    generate_crime_list_pdf,
    generate_single_crime_pdf,
    generate_analysis_pdf,
)
from .generators.excel_generator import generate_crime_list_excel

logger = logging.getLogger('apps.reports')


# ─────────────────────────────────────────────────────────────
# HELPER
# ─────────────────────────────────────────────────────────────
def save_report_file(buffer, filename, report_obj):
    from django.core.files.base import ContentFile
    report_obj.file.save(filename, ContentFile(buffer.read()))
    buffer.seek(0)


# ─────────────────────────────────────────────────────────────
# CRIME LIST REPORT
# ─────────────────────────────────────────────────────────────
@extend_schema(
    tags=['📄 Reports'],
    summary='Generate a crime list report (PDF or Excel)',
    description='Generates and downloads a formatted crime list report. Apply optional filters.',
    examples=[
        OpenApiExample(
            'Filter by District',
            value={'district': 'Kampala', 'severity': 'high'},
            request_only=True,
        )
    ]
)
class CrimeListReportView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, format_type):
        category = request.data.get('category')
        status_  = request.data.get('status')
        district = request.data.get('district')
        severity = request.data.get('severity')

        filters = {}
        reports = CrimeReport.objects.all().order_by('-date_reported')

        if category:
            reports = reports.filter(category=category)
            filters['category'] = category
        if status_:
            reports = reports.filter(status=status_)
            filters['status'] = status_
        if district:
            reports = reports.filter(district__icontains=district)
            filters['district'] = district
        if severity:
            reports = reports.filter(severity=severity)
            filters['severity'] = severity

        reports = list(reports)

        report_record = GeneratedReport.objects.create(
            generated_by = request.user,
            title        = f"Crime List Report — {timezone.now().strftime('%Y-%m-%d %H:%M')}",
            report_type  = ReportType.CRIME_LIST,
            report_format= format_type,
            parameters   = filters,
        )

        timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')

        try:
            if format_type == ReportFormat.PDF:
                buffer   = generate_crime_list_pdf(reports, filters)
                filename = f"crime_list_{timestamp}.pdf"
                save_report_file(buffer, filename, report_record)
                logger.info(f"PDF report generated by {request.user.badge_number}")
                return FileResponse(
                    buffer, as_attachment=True,
                    filename=filename, content_type='application/pdf'
                )
            elif format_type == ReportFormat.EXCEL:
                buffer   = generate_crime_list_excel(reports, filters)
                filename = f"crime_list_{timestamp}.xlsx"
                save_report_file(buffer, filename, report_record)
                logger.info(f"Excel report generated by {request.user.badge_number}")
                return FileResponse(
                    buffer, as_attachment=True,
                    filename=filename,
                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )
            else:
                return Response(
                    {'error': 'Invalid format. Use pdf or excel.'},
                    status=status.HTTP_400_BAD_REQUEST
                )
        except Exception as e:
            logger.error(f"Report generation error: {e}")
            return Response(
                {'error': f'Report generation failed: {str(e)}'},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


# ─────────────────────────────────────────────────────────────
# SINGLE CRIME PDF
# ─────────────────────────────────────────────────────────────
@extend_schema(
    tags=['📄 Reports'],
    summary='Download a single crime case as PDF',
    description='Generates a detailed PDF report for one specific crime case.',
)
class SingleCrimeReportView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, case_number):
        try:
            report = CrimeReport.objects.get(case_number=case_number)
        except CrimeReport.DoesNotExist:
            return Response(
                {'error': f'Crime report {case_number} not found.'},
                status=status.HTTP_404_NOT_FOUND
            )
        try:
            buffer   = generate_single_crime_pdf(report)
            filename = f"{case_number}_report.pdf"
            report_record = GeneratedReport.objects.create(
                generated_by  = request.user,
                title         = f"Crime Report — {case_number}",
                report_type   = ReportType.SINGLE_CRIME,
                report_format = ReportFormat.PDF,
                parameters    = {'case_number': case_number},
            )
            save_report_file(buffer, filename, report_record)
            logger.info(f"Single crime PDF generated: {case_number}")
            return FileResponse(
                buffer, as_attachment=True,
                filename=filename, content_type='application/pdf'
            )
        except Exception as e:
            logger.error(f"Single crime PDF error: {e}")
            return Response(
                {'error': f'Report generation failed: {str(e)}'},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


# ─────────────────────────────────────────────────────────────
# ANALYSIS PDF
# ─────────────────────────────────────────────────────────────
@extend_schema(
    tags=['📄 Reports'],
    summary='Download an AI analysis result as PDF',
    description='Generates a formatted PDF report from a completed AI analysis.',
)
class AnalysisReportView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, pk):
        try:
            analysis = AnalysisResult.objects.get(pk=pk)
        except AnalysisResult.DoesNotExist:
            return Response(
                {'error': 'Analysis result not found.'},
                status=status.HTTP_404_NOT_FOUND
            )
        if analysis.status != 'completed':
            return Response(
                {'error': 'Analysis is not completed yet.'},
                status=status.HTTP_400_BAD_REQUEST
            )
        try:
            buffer   = generate_analysis_pdf(analysis)
            filename = f"analysis_{pk}_report.pdf"
            report_record = GeneratedReport.objects.create(
                generated_by  = request.user,
                title         = f"AI Analysis Report — ID {pk}",
                report_type   = ReportType.ANALYSIS,
                report_format = ReportFormat.PDF,
                parameters    = {'analysis_id': pk},
            )
            save_report_file(buffer, filename, report_record)
            logger.info(f"Analysis PDF generated: ID {pk}")
            return FileResponse(
                buffer, as_attachment=True,
                filename=filename, content_type='application/pdf'
            )
        except Exception as e:
            logger.error(f"Analysis PDF error: {e}")
            return Response(
                {'error': f'Report generation failed: {str(e)}'},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


# ─────────────────────────────────────────────────────────────
# REPORT HISTORY
# ─────────────────────────────────────────────────────────────
@extend_schema(
    tags=['📄 Reports'],
    summary='List all previously generated reports',
    description='Returns a history of all reports generated by the logged-in officer.',
)
class ReportHistoryView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        reports    = GeneratedReport.objects.filter(
            generated_by=request.user
        ).order_by('-created_at')
        serializer = GeneratedReportSerializer(reports, many=True)
        return Response({
            'count':   reports.count(),
            'results': serializer.data,
        }, status=status.HTTP_200_OK)