# Generated by Django 6.0.2 on 2026-02-26 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('crime_list', 'Crime List Report'), ('single_crime', 'Single Crime Report'), ('analysis', 'AI Analysis Report'), ('statistics', 'Statistics Report'), ('district', 'District Report')], default='crime_list', max_length=20)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
